### ISSUE TITLE
Solar panel support

### ISSUE THREAD

**Issue by jkufner** [ApolloAutomation/PLT-1#10]
It would be nice if the sensor had a small solar panel. It could feed the battery and eliminate the need for cables. Plants are typically placed in sunny areas, so it goes well together.

I've built a similar sensor using M5Core-Ink and Imou FSP13 solar panel (which is way too big for this application). The M5Core-Ink lasts for a week on its internal batter without the solar panel, while the solar panel fully charges it in a few minutes. I tried using an ESP32 without a battery, only with a small raw solar panel, but it does not work - the power consumption peaks too high.

Having a lithium battery in each plant may be somewhat a fire hazzard, so I would suggest exploring supercapacitor alternatives.

The integration of the solar charger into the sensor enables the sensor to wake up when there is enough charge to measure and send the data, rather than guessing how many minutes it needs to charge. The wake-up can be implemented using a voltage comparator and GPIO wake up, or it can be software-only, where the ESP first measures the battery voltage and only if it is high enough, it enables wifi and does the measurment.

**Comment by TrevorSchirmer** [comment]
Thanks so much for the suggestion. Our beta units actually had a solar plug port and a mount for a solar panel. It all worked great but we decided on the production PLT-1B to not include onboard charging. This was simply due to simplifying and not having the responsibility for the charging circuit. It is something we want to explore in the future but don't have a plan for currently.
