### ISSUE TITLE
Incorrect sensor value when using offsets

### ISSUE THREAD

**Issue by RLProteus** [ApolloAutomation/PLT-1#13]
Configuring offsets for Air Temp and Humidity sensors results in an output that is incorrect. Setting the inverse of the desired offset results in the expected adjustment to the sensor value.

ie. If the current temperature reading is 70 and I want to add an offset of -5, with the current formula the result would be 70 - -5 = 75. New formula would result in 70 + -5 = 65

I believe I have addressed the issue in PR https://github.com/ApolloAutomation/PLT-1/pull/12 but let me know if I'm missing something. 

Thanks!

**Comment by TrevorSchirmer** [comment]
Hello, thanks so much for taking the time to reach out to us.

I understand the logic in your change and agree it is more true. However back when we released the MSR-1 we talked to the community extensively about the offset because there was a lot of confusion using the negative values. Since the offset is almost always to compensate for the heat in the case. So we've had the same offset calculation in all of our sensors and documentation since then. That is the reason we already do the subtraction in our formula to make the offset number a positive value.

**Comment by RLProteus** [comment]
Understood. I figured there had to be a reason I just couldn't find anything on the wiki.

From a first time user experience it wasn't what I expected when adjusting the offset (and yes I was adjusting for the ESP heat 😅). Took me a few tires and checking the config to understand why I was seeing these results.

Does it make sense to add a note to [this part of the docs](https://github.com/ApolloAutomation/docs/blob/main/docs/products/general/temp-hum-calibration.md#bme280--scd40-sensors-overcoming-temperature--humidity-reading-challenges) calling out that the offset is inverted for user convenience?

**Comment by null-affinity** [comment]
This perplexed me as well, and I really wish the offset was the more correct variant: minus means minus, plus means plus.

**Comment by TrevorSchirmer** [comment]
@RLProteus Yes we'll update the wiki @Bunton33 can we get it on the list for wiki corrections?

@null-affinity I understand your point. It was just a decision we made based on feedback initially since the offset would always be a negative. Having it be a negative confused a lot more people so we decided to make it a positive on all of our devices.
